---
models:
  user:
  - &5
    email: arry@citizenlab.co
    first_name: Jean
    last_name: Demarest
    locale: en
    bio_multiloc:
      en: 
    gender: male
    birthyear: 
    domicile: outside
    education: 2
    password: Au0n1Lf2pdg
    remote_avatar_url: http://i0.kym-cdn.com/entries/icons/original/000/000/091/TrollFace.jpg
  - &7
    email: princesslea@gmail.com
    first_name: Lea
    last_name: Skywalker
    locale: en
    bio_multiloc:
      en: 
    gender: female
    birthyear: 1965
    domicile: outside
    education: 1
    password: helpmeOB1
    remote_avatar_url: http://images2.fanpop.com/image/photos/9300000/leia-princess-leia-organa-solo-skywalker-9301321-576-1010.jpg
  - &9
    email: bonjoursalut@gmail.com
    first_name: Loïc
    last_name: Didier
    locale: en
    bio_multiloc:
      en: 
    gender: male
    birthyear: 1937
    domicile: outside
    education: 5
    password: chCKpa8noMk
    remote_avatar_url: https://d34jodf30bmh8b.cloudfront.net/pictures/5661/5804/profile-1474295964-7c5694e2fc409f9ba430e094fee7f906.jpg
  - &10
    email: hello@citoyen.fr
    first_name: Simone
    last_name: Weil
    locale: en
    bio_multiloc:
      en: 
    gender: female
    birthyear: 1938
    domicile: outside
    education: 8
    password: 1xriCKUHbfc
    remote_avatar_url: http://www.femmescelebres.com/wp-content/uploads/2009/09/simoneveil1.jpg
  - &11
    email: changerlemonde@now.org
    first_name: Jamie
    last_name: Oliver
    locale: en
    bio_multiloc:
      en: 
    gender: male
    birthyear: 1968
    domicile: outside
    education: 3
    password: 3FV9KPlMijU
    remote_avatar_url: https://pbs.twimg.com/profile_images/747932549494628352/lwE6mkkk.jpg
  - &13
    email: lavieestbelle@gmail.com
    first_name: 'Philippe '
    last_name: De Belgique
    locale: en
    bio_multiloc:
      en: 
    gender: male
    birthyear: 1973
    domicile: 
    education: 3
    password: Omkz_-gSqH4
    remote_avatar_url: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLIl3M4LpUcNkuHa4_f2r4bmuIlt9-yD8O4KjA_3Q8xetsiPsa
  topic:
  - title_multiloc: topics.infrastructure
    description_multiloc: topics.infrastructure_description
  - &21
    title_multiloc: topics.waste
    description_multiloc: topics.waste_description
  - &20
    title_multiloc: topics.mobility
    description_multiloc: topics.mobility_description
  - title_multiloc: topics.technology
    description_multiloc: topics.technology_description
  - title_multiloc: topics.economy
    description_multiloc: topics.economy_description
  - &22
    title_multiloc: topics.nature
    description_multiloc: topics.nature_description
  - title_multiloc: topics.sustainability
    description_multiloc: topics.sustainability_description
  - title_multiloc: topics.housing
    description_multiloc: topics.housing_description
  - &23
    title_multiloc: topics.culture
    description_multiloc: topics.culture_description
  - title_multiloc: topics.citizenship
    description_multiloc: topics.citizenship_description
  - title_multiloc: topics.social
    description_multiloc: topics.social_description
  - title_multiloc: topics.health
    description_multiloc: topics.health_description
  idea_status:
  - title_multiloc: statuses.proposed
    ordering: 100
    code: proposed
    color: "#687782"
    description_multiloc: statuses.proposed_description
  - &6
    title_multiloc: statuses.under_consideration
    ordering: 200
    code: under_consideration
    color: "#0080A5"
    description_multiloc: statuses.under_consideration_description
  - title_multiloc: statuses.accepted
    ordering: 300
    code: accepted
    color: "#04884C"
    description_multiloc: statuses.accepted_description
  - &12
    title_multiloc: statuses.rejected
    ordering: 400
    code: rejected
    color: "#E52516"
    description_multiloc: statuses.rejected_description
  - &8
    title_multiloc: statuses.implemented
    ordering: 500
    code: implemented
    color: "#04884C"
    description_multiloc: statuses.implemented_description
  project:
  - &1
    title_multiloc:
      en: Comment améliorer la mobilité dans votre ville
    description_multiloc:
      en: "<p>Contribuez à création d&#39;une ville durable où la mobilité est réfléchie
        et intermodale. Soyez créatifs afin de trouver des solutions innovantes pour
        s&#39;adapter aux nouveaux modes de déplacements. </p>\n"
    remote_header_bg_url: 
  - &2
    title_multiloc:
      en: Une meilleure gestion de nos déchets
    description_multiloc:
      en: "<p>Chaque année, un habitant produit 354 kg d’ordures ménagères. En prenant
        en compte la quantité de déchets municipaux par habitant, la quantité produite
        monte alors à 536 kg par an. Réduire la quantité de déchets est un enjeu environnemental,
        financier et sociétal. </p>\n"
    remote_header_bg_url: 
  - &3
    title_multiloc:
      en: Aménagement des espaces verts
    description_multiloc:
      en: "<p>Les parcs et pelouses constituent un havre de paix dans une ville animée.
        Ces espaces peuvent être de véritables refuges de détente pour l&#39;habitant,
        apropriez-vous cet espace public en soumettant vos propositions! </p>\n"
    remote_header_bg_url: 
  - &4
    title_multiloc:
      en: Démocratiser la culture
    description_multiloc:
      en: "<p>Selon l&#39;UNESCO, la culture peut aujourd’hui être considérée comme
        l&#39;ensemble des traits distinctifs, spirituels , matériels, intellectuels
        et affectifs, qui caractérisent une société ou un groupe social. Se l&#39;approprier
        est primordial pour la cohésion de la société et des habitants de notre ville.
        Ainsi, comment rendre la culture plus accessible à tous?</p>\n"
    remote_header_bg_url: 
  project_image:
  - remote_image_url: http://static.tvtropes.org/pmwiki/pub/images/rsz_fd6e28f288acfdc7a88b43f8bd3181af57f3cf8a.png
    project_ref: *1
  - remote_image_url: https://www.grandlyon.com/fileadmin/user_upload/media/images/nature/nature_parcdegerland_ldaniere_860.jpg
    project_ref: *3
  - remote_image_url: http://www.prun.net/im/article/normal/2014-01-15-8b89955f5156c785ba1b9859bbc0e247.jpg
    project_ref: *4
  idea:
  - &14
    title_multiloc:
      en: Créer une aire de covoiturage au centre de la ville
    body_multiloc:
      en: "<p>La pratique du covoiturage explose face à l&#39;inflation des prix des
        transports en commun. Afin de faciliter et d&#39;encourager cette pratique
        bénéfique pour les habitants d&#39;une ville, il faudrait prévoir des espaces
        réservés dans l&#39;espace public. </p>\n"
    author_ref: *5
    project_ref: *1
    areas: []
    idea_status_ref: *6
    publication_status: published
  - &15
    title_multiloc:
      en: Multiplier les bacs de compost urbain
    body_multiloc:
      en: "<p>La moitié de nos poubelles sont composées d&#39;éléments organiques
        qui devraient revenir à la terre au lieu d&#39;être brûlés dans des crématoires
        qui émettent une quantité importante de dioxyde de carbone dans l&#39;atmosphère.
        Il faut multiplier les points de compost dans la ville pour rendre cette pratique
        accessible à tous. De plus, le compost est un engrais indispensable pour les
        jardins partagés qui fleurissent partout à travers la ville. Autoriser ces
        points de compost c&#39;est aussi donner les clés du quartier aux habitants
        qui s&#39;approprient leur territoire en devenant co-acteur. Les dernières
        expériences de compost partagés montrent que des personnes isolées parviennent
        à recréer du lien avec les autres habitants de leur quartier. Ainsi pour un
        voisinage de qualité, une réduction des émissions carbonique dans l&#39;atmosphère
        et des jardins partagés féconds grâce à un engrais local, je vous invite à
        soutenir cette initiative. Votez pour! </p>\n"
    author_ref: *7
    project_ref: *2
    areas: []
    idea_status_ref: *8
    publication_status: published
  - &16
    title_multiloc:
      en: Verbaliser les conducteurs seuls d'une infraction de première classe
    body_multiloc:
      en: "<p>Une voiture pèse en moyenne 1200 kg et mesure plus de 4 mètres soit
        17 fois plus lourd qu&#39;un homme et deux fois et demi sa taille. La solution
        aux bouchons, nuisances sonores et aux pollutions urbaines est alors toute
        simple: interdire la voiture aux personnes qui pourraient s&#39;en passer.
        Pour faire preuve de pragmatisme, j&#39;aimerais que l&#39;on commence à interdire
        la voiture aux personnes qui ne cherchent pas à reduire leur empreinte carbone.
        La qualité de l&#39;air et l&#39;environnement est une affaire de tous! Des
        actions courageuses auraient dû être prises il y a déjà longtemps, nous n&#39;avons
        plus le luxe de revendiquer notre confort personnel. En ne faisant rien, les
        générations à venir se souviendront de nous comme des criminels égoistes ayant
        refusé la créativité politique pour répondre à l&#39;urgence environnementale.
        </p>\n"
    author_ref: *9
    project_ref: *1
    areas: []
    idea_status_ref: *8
    publication_status: published
  - &17
    title_multiloc:
      en: Rénovation du Parc de l'église
    body_multiloc:
      en: "<p>Le parc de l&#39;église mériterait une plaine de jeu pour les enfants
        de la ville ; faisons appel à un paysagiste et redonnons à ce parc son utilité
        premère au coeur de la ville.</p>\n"
    author_ref: *10
    project_ref: *3
    areas: []
    idea_status_ref: *6
    publication_status: published
  - &18
    title_multiloc:
      en: Offrir des places de théatre aux nouveaux bacheliers
    body_multiloc:
      en: "<p>La culture est essentielle pour notre jeunesse, nous proposons d&#39;offrir
        des places de théatre à tous les jeunes ayant obtenus ou non leur baccalauréat.</p>\n"
    author_ref: *11
    project_ref: *4
    areas: []
    idea_status_ref: *12
    publication_status: published
  - &19
    title_multiloc:
      en: Ne plus avoir des poubelles en plastiques pour le rammassage des ordures
    body_multiloc:
      en: "<p>L&#39;idée est de réduire le plastique utilisé dans la collecte des
        ordures ; nous mettrions les poubelles directement dans la rue en nous débarrassant
        des containers</p>\n"
    author_ref: *13
    project_ref: *2
    areas: []
    idea_status_ref: *8
    publication_status: published
  vote:
  - mode: up
    user_ref: *5
    votable_ref: *14
  - mode: up
    user_ref: *13
    votable_ref: *14
  - mode: up
    user_ref: *10
    votable_ref: *14
  - mode: up
    user_ref: *9
    votable_ref: *14
  - mode: up
    user_ref: *11
    votable_ref: *14
  - mode: down
    user_ref: *7
    votable_ref: *14
  - mode: up
    user_ref: *5
    votable_ref: *15
  - mode: up
    user_ref: *10
    votable_ref: *15
  - mode: up
    user_ref: *13
    votable_ref: *15
  - mode: down
    user_ref: *7
    votable_ref: *15
  - mode: down
    user_ref: *9
    votable_ref: *15
  - mode: up
    user_ref: *13
    votable_ref: *16
  - mode: up
    user_ref: *5
    votable_ref: *16
  - mode: down
    user_ref: *7
    votable_ref: *16
  - mode: down
    user_ref: *10
    votable_ref: *16
  - mode: down
    user_ref: *11
    votable_ref: *16
  - mode: up
    user_ref: *5
    votable_ref: *17
  - mode: up
    user_ref: *13
    votable_ref: *17
  - mode: up
    user_ref: *7
    votable_ref: *17
  - mode: up
    user_ref: *11
    votable_ref: *17
  - mode: up
    user_ref: *10
    votable_ref: *17
  - mode: up
    user_ref: *9
    votable_ref: *17
  - mode: up
    user_ref: *5
    votable_ref: *18
  - mode: up
    user_ref: *10
    votable_ref: *18
  - mode: up
    user_ref: *11
    votable_ref: *18
  - mode: down
    user_ref: *9
    votable_ref: *18
  - mode: down
    user_ref: *13
    votable_ref: *18
  - mode: up
    user_ref: *9
    votable_ref: *19
  - mode: down
    user_ref: *13
    votable_ref: *19
  - mode: down
    user_ref: *7
    votable_ref: *19
  - mode: down
    user_ref: *5
    votable_ref: *19
  - mode: down
    user_ref: *11
    votable_ref: *19
  - mode: down
    user_ref: *10
    votable_ref: *19
  ideas_topic:
  - idea_ref: *14
    topic_ref: *20
  - idea_ref: *15
    topic_ref: *21
  - idea_ref: *16
    topic_ref: *20
  - idea_ref: *17
    topic_ref: *22
  - idea_ref: *18
    topic_ref: *23
  - idea_ref: *19
    topic_ref: *21
  idea_image:
  - remote_image_url: http://test.hanvecforum.fr/wp-content/uploads/2015/11/covoiturage2.jpg
    idea_ref: *14
  - remote_image_url: http://daxushequ.com/data/out/64/img60353749.jpg
    idea_ref: *15
  - remote_image_url: http://transports.blog.lemonde.fr/files/2015/09/Bikes-vs-cars-1-900x506.jpg
    idea_ref: *16
  - remote_image_url: https://s-media-cache-ak0.pinimg.com/originals/e3/97/e4/e397e41f31bd66d503a5e17ff7b0bca5.jpg
    idea_ref: *17
  - remote_image_url: http://daxushequ.com/data/out/64/img60353749.jpg
    idea_ref: *18
  - remote_image_url: http://daxushequ.com/data/out/64/img60353749.jpg
    idea_ref: *19
  comment:
  - &24
    body_multiloc:
      en: "<p>Super idée ; je vous soutiens ! </p>\n"
    author_ref: *7
    idea_ref: *14
    parent_ref: 
  - body_multiloc:
      en: "<p>Pourquoi pas, c&#39;est une bonne idée ! </p>\n"
    author_ref: *5
    idea_ref: *14
    parent_ref: *24
  - body_multiloc:
      en: "<p>Pourquoi s&#39;arrêter en si bon chemin, nous pourrions également penser
        à intégrer tout ceci dans une démarche de smartcity ... Qu&#39;en pensez-vous
        ?</p>\n"
    author_ref: *5
    idea_ref: *14
    parent_ref: 
  event:
  - title_multiloc:
      en: Pub Crawl
    description_multiloc:
      en: |
        <p>Grab your bicycle and go on a pub crawl with us. Subscription fee is 15€, all drinks are free!</p>

        <p>No animals allowed.</p>
    location_multiloc:
      en: Many different pubs, we start from the central place.
    project_ref: *1
    start_at: 2018-09-16
    end_at: 2018-09-17
  phase:
  - title_multiloc:
      en: Récolte d'idéees
    description_multiloc:
      en: "<p>La première phase consiste à récolter tous les projets auprès des citoyens</p>\n"
    project_ref: *1
    start_at: 2017-02-19
    end_at: 2017-04-24
  - title_multiloc:
      en: Votes
    description_multiloc:
      en: "<p>Cette phase laisse le temps aux citoyens de plébiciter les idées qui
        leur semblent les plus pertinentes et réalistes</p>\n"
    project_ref: *1
    start_at: 2017-04-24
    end_at: 2017-06-16
  - title_multiloc:
      en: Résultats de votes
    description_multiloc:
      en: "<p>Les résultats du vote citoyen sont annocés</p>\n"
    project_ref: *1
    start_at: 2017-06-16
    end_at: 2017-08-03
  - title_multiloc:
      en: Implémentation des projets retenus
    description_multiloc:
      en: "<p>Mise en place des projets retenus </p>\n"
    project_ref: *1
    start_at: 2017-08-03
    end_at: 2017-11-27
