---
models:
  user:
  - &5
    email: arry@citizenlab.co
    first_name: Arry
    last_name: Snow
    locale: en
    bio_multiloc:
      en: 
    gender: male
    birthyear: 1974
    domicile: outside
    education: 
    password: 5oaIqe41Zxs
    remote_avatar_url: http://i0.kym-cdn.com/entries/icons/original/000/000/091/TrollFace.jpg
  - &2
    email: princesslea@gmail.com
    first_name: Lea
    last_name: Skywalker
    locale: en
    bio_multiloc:
      en: 
    gender: female
    birthyear: 1945
    domicile: outside
    education: 7
    password: helpmeOB1
    remote_avatar_url: http://images2.fanpop.com/image/photos/9300000/leia-princess-leia-organa-solo-skywalker-9301321-576-1010.jpg
  topic:
  - title_multiloc: topics.infrastructure
    description_multiloc: topics.infrastructure_description
  - title_multiloc: topics.waste
    description_multiloc: topics.waste_description
  - &6
    title_multiloc: topics.mobility
    description_multiloc: topics.mobility_description
  - title_multiloc: topics.technology
    description_multiloc: topics.technology_description
  - title_multiloc: topics.economy
    description_multiloc: topics.economy_description
  - title_multiloc: topics.nature
    description_multiloc: topics.nature_description
  - title_multiloc: topics.sustainability
    description_multiloc: topics.sustainability_description
  - title_multiloc: topics.housing
    description_multiloc: topics.housing_description
  - title_multiloc: topics.culture
    description_multiloc: topics.culture_description
  - title_multiloc: topics.citizenship
    description_multiloc: topics.citizenship_description
  - title_multiloc: topics.social
    description_multiloc: topics.social_description
  - title_multiloc: topics.health
    description_multiloc: topics.health_description
  idea_status:
  - title_multiloc: statuses.proposed
    ordering: 100
    code: proposed
    color: "#687782"
    description_multiloc: statuses.proposed_description
  - &3
    title_multiloc: statuses.under_consideration
    ordering: 200
    code: under_consideration
    color: "#0080A5"
    description_multiloc: statuses.under_consideration_description
  - title_multiloc: statuses.accepted
    ordering: 300
    code: accepted
    color: "#04884C"
    description_multiloc: statuses.accepted_description
  - title_multiloc: statuses.rejected
    ordering: 400
    code: rejected
    color: "#E52516"
    description_multiloc: statuses.rejected_description
  - title_multiloc: statuses.implemented
    ordering: 500
    code: implemented
    color: "#04884C"
    description_multiloc: statuses.implemented_description
  project:
  - &1
    title_multiloc:
      en: Reducing Air Pollution in the City
    description_multiloc:
      en: |
        <p><a href="https://en.wikipedia.org/wiki/Global_warming">Global warming</a> is becoming an increasing concern of our society. Your city wants to <strong>fight</strong> the air pollution! </p>

        <p>You can support this innitiative by proposing your ideas on how to tackle this issue.</p>

        <p><em>Let&#39;s do this!</em></p>
    remote_header_bg_url: 
  project_image:
  - remote_image_url: http://static.tvtropes.org/pmwiki/pub/images/rsz_fd6e28f288acfdc7a88b43f8bd3181af57f3cf8a.png
    project_ref: *1
  idea:
  - &4
    title_multiloc:
      en: More Bicycle Racks
    body_multiloc:
      en: "<p>Title says it all.</p>\n"
    author_ref: *2
    project_ref: *1
    areas: []
    idea_status_ref: *3
    publication_status: published
  vote:
  - mode: up
    user_ref: *2
    votable_ref: *4
  - mode: up
    user_ref: *5
    votable_ref: *4
  ideas_topic:
  - idea_ref: *4
    topic_ref: *6
  idea_image: []
  comment:
  - &7
    body_multiloc:
      en: "<p>Great idea, we stand behind you!</p>\n"
    author_ref: *2
    idea_ref: *4
    parent_ref: 
  - body_multiloc:
      en: "<p>I&#39;ve never seen you riding a bicycle...</p>\n"
    author_ref: *5
    idea_ref: *4
    parent_ref: *7
  - body_multiloc:
      en: "<p>Why stop there? The city also lacks stables. There should at least be
        one near the river.</p>\n"
    author_ref: *5
    idea_ref: *4
    parent_ref: 
  event:
  - title_multiloc:
      en: Pub Crawl
    description_multiloc:
      en: |
        <p>Grab your bicycle and go on a pub crawl with us. Subscription fee is 15€, all drinks are free!</p>

        <p>No animals allowed.</p>
    location_multiloc:
      en: Many different pubs, we start from the central place.
    project_ref: *1
    start_at: 2017-08-11
    end_at: 2017-08-12
  phase:
  - title_multiloc:
      en: Cyclist Invasion
    description_multiloc:
      en: "<p>The first phase consists of increasing the amount of cyclists in the
        city.</p>\n"
    project_ref: *1
    start_at: 2018-08-08
    end_at: 2018-10-21
  - title_multiloc:
      en: Autocar Expelsion
    description_multiloc:
      en: "<p>Next, we will hunt away cars and trucks from the inner city. Only busses
        are welcome!</p>\n"
    project_ref: *1
    start_at: 2018-10-21
    end_at: 2018-12-08
  - title_multiloc:
      en: Breathe Fresh Air
    description_multiloc:
      en: "<p>Finally, we can enjoy breathing fresh, clean air.</p>\n"
    project_ref: *1
    start_at: 2018-12-08
    end_at: 2018-12-30
